[유하람] 게시물 상세조회
wecode-bootcamp-korea/15-1st-DMFriends-backend pull request #11
Opened 2020-12-22 01:35 UTC by haileeCoder

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 게시물 상세조회 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- query string을 통해 board_id와 sort를 입력받는다.
- sort 여부에 따라 댓글 정렬 방식을 변경할 수 있다. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 좋아요를 기준으로 댓글 정렬하는 효율적인 방법이 궁금합니다. 
- 새로운 딕셔너리 내에 댓글id, 좋아요 수를 기준으로 담은 뒤 재정렬하여 댓글을 다시 호출하는.. 방법은 너무 비효율적인 것 같아..
우선 게시물 좋아요, 댓글 작성 기능부터 구현한 뒤 다시 수정하려 합니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-22 14:01 UTC, ulfrid requested changes
Post를 가져오는 뷰와 Comment를 가져오는 뷰를 나눠서 작성하고 프론트에 개별 호출 하도록 만들기
페이지네이션 도전해보기 offset: limit

2020-12-23 04:35 UTC, ulfrid requested changes

2020-12-23 04:35 UTC, ulfrid commented on board/views.py
> +            print(board_data)
```suggestion
            print(board_data)
```
제거 부탁드립니다.

2020-12-23 08:52 UTC, devops-andrew commented on board/urls.py
> +    path('/comment', GetCommentView.as_view()),
GetCommentView , AddCommentView 를 합쳐서! 하나의 CommentView로 작성 부탁드리고, 메서드로 구분해주세요.

2020-12-23 08:52 UTC, devops-andrew commented on board/views.py
> +        except Board.MultipleObjectsReturned:
실제 확인된 에러만 걸어 주세요!

2020-12-23 10:26 UTC, ulfrid requested changes

2020-12-23 10:26 UTC, ulfrid commented on board/views.py
> +                if BoardLike.objects.filter(board_id=board_id, member_id=member_id)[0].is_like == 1:
```suggestion
                if BoardLike.objects.filter(board_id=board_id, member_id=member_id)[0].is_like == 1:
```
하나의 게시물에 유저가 좋아요를 남길경우는 한번이므로 get().is_like==1이 낫지 않을까요?

2020-12-23 10:26 UTC, ulfrid commented on board/views.py
> +                else:
else: 줄이는 습관을 부탁드립니다!

2020-12-23 10:26 UTC, ulfrid commented on board/views.py
> +        except :
BoardLike.DoesNotExist 를 써야 할 것 같아요.

2020-12-23 10:26 UTC, ulfrid commented on board/views.py
> +            return JsonResponse({'message' : 'NO_LIKE_EXIST'}, status = 500)
위의 코드와 유사하므로 같이 고쳐 주세요!

2020-12-23 15:20 UTC, ulfrid requested changes

2020-12-23 15:20 UTC, ulfrid commented on board/views.py
> +                member_id = 0
메서드 만들었으니까 이건 빼주세요.

2020-12-23 15:20 UTC, ulfrid commented on board/views.py
> +                "if_i_liked"    : check_boardLike(self, request, board.id),
```suggestion
                "member_liked"    : check_boardLike(self, request, board.id),
```

2020-12-23 15:20 UTC, ulfrid commented on board/views.py
> +            if request.user != None:
```suggestion
            if request.user:
```

2020-12-23 15:20 UTC, ulfrid commented on board/views.py
> +                return JsonResponse({"message" : "INVALID_USER"}, status=400) ## 확인부탁드려요!!
로그인 데코레이터로 바꾸면 필요 없을것 같습니다.

2020-12-23 15:20 UTC, ulfrid commented on board/views.py
> +                    return JsonResponse({'message' : 'COMMENT_REQUIRED'}, status=400)
이건 여기 내부가 아니라 위에서 할 처리 같아요.

2020-12-23 15:20 UTC, ulfrid commented on board/views.py
> +                elif Comment.objects.filter(id=comment_id).exists():
```suggestion
                if Comment.objects.filter(id=comment_id).exists():
```
위에 내용검증 content 아래로 옮기면 여긴 이렇게 바꾸면 되겠죠.

2020-12-23 15:20 UTC, ulfrid commented on board/views.py
> +            if board_id and member_id:
```suggestion
            if board_id and request.user:
```

2020-12-23 15:20 UTC, ulfrid commented on board/views.py
> +                return JsonResponse({"message" : "INVALID_USER"}, status=400)
마찬가지로 데코레이터를 교체합시다.

2020-12-23 15:21 UTC, haileeCoder commented on board/urls.py
> +    path('/comment', GetCommentView.as_view()),
확인했습니다!

2020-12-23 15:21 UTC, haileeCoder commented on board/views.py
> +        except Board.MultipleObjectsReturned:
확인했습니다!

2020-12-23 15:22 UTC, haileeCoder commented on board/views.py
> +                if BoardLike.objects.filter(board_id=board_id, member_id=member_id)[0].is_like == 1:
확인했습니다!

2020-12-23 15:22 UTC, haileeCoder commented on board/views.py
> +                else:
확인했습니다!

2020-12-23 15:22 UTC, haileeCoder commented on board/views.py
> +        except :
확인했습니다!

2020-12-23 15:22 UTC, haileeCoder commented on board/views.py
> +            return JsonResponse({'message' : 'NO_LIKE_EXIST'}, status = 500)
확인했습니다!

2020-12-23 15:47 UTC, haileeCoder commented on board/views.py
> +                member_id = 0
확인했습니다.

2020-12-23 15:48 UTC, haileeCoder commented on board/views.py
> +                "if_i_liked"    : check_boardLike(self, request, board.id),
수정했습니다!

2020-12-23 16:08 UTC, ulfrid requested changes
정말 마지막 수정!!!

2020-12-23 16:08 UTC, ulfrid commented on board/views.py
> +            return JsonResponse({'message' : 'NO_EXIST_DATA'}, status = 500)
```suggestion
            return JsonResponse({'message' : 'COMMENT_DOES_NOT_EXIST'}, status = 404)        
```

2020-12-23 16:08 UTC, ulfrid commented on board/views.py
> +            return JsonResponse({'message' : 'NO_COMMENT_EXIST'}, status = 500)
```suggestion
        except :
            return JsonResponse({'message' : 'NO_COMMENT_EXIST'}, status = 500)
```
이코드는 없는게 나은 코드입니다.

2020-12-23 16:08 UTC, ulfrid commented on board/views.py
> +            return JsonResponse({'message' : 'NO_COMMENT_EXIST'}, status = 500)
```suggestion
        except :
            return JsonResponse({'message' : 'NO_COMMENT_EXIST'}, status = 500) 
```
제거해주세요.

2020-12-23 16:08 UTC, ulfrid commented on board/views.py
> +            return JsonResponse({'message' : 'NO_EXIST_DATA'}, status = 500)
```suggestion
            return JsonResponse({'message' : 'NO_EXIST_DATA'}, status = 404)    
```

2020-12-23 16:08 UTC, ulfrid commented on board/views.py
> +            data = Board.objects.filter(id = board_id)[0]
```suggestion
            data = Board.objects.filter(id = board_id).first()
```
아니면
```suggestion
            data = Board.objects.get(id = board_id)
```

2020-12-23 16:08 UTC, ulfrid commented on board/views.py
>              return JsonResponse({'message' : 'TOO_MANY_DATA'}, status = 500)
제거하는게 좋은 코드 입니다

2020-12-23 16:08 UTC, ulfrid commented on board/views.py
>              return JsonResponse({'message' : 'NO_EXIST_DATA'}, status = 500)
```suggestion
            return JsonResponse({'message' : 'BOARD_DOES_NOT_EXIST'}, status = 404)
```

2020-12-23 16:08 UTC, ulfrid commented on board/views.py
> +            return JsonResponse({'message' : 'NO_LIKE_EXIST'}, status = 500)
없어도 될것 같아요 
```suggestion
            return JsonResponse({'message' : 'NO_LIKE_EXIST'}, status = 500) 
```

2020-12-23 16:08 UTC, ulfrid commented on board/views.py
> +            return JsonResponse({'message' : 'NO_LIKE_EXIST'}, status = 500)
없어도 될것 같아요

2020-12-23 16:22 UTC, ulfrid commented
LGTM.

2020-12-23 16:22 UTC, merged