[이승연] Modify: 카트에 담긴 상품 반환 시 이미지 반환하도록  추가
wecode-bootcamp-korea/15-1st-DMFriends-backend pull request #13
Opened 2020-12-23 08:36 UTC by lyla0427

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카트에 담긴 상품 반환 시 이미지 반환하도록  추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-23 17:46 UTC, jamessoun93 requested changes

2020-12-23 17:46 UTC, jamessoun93 commented on order/views.py
> +            "image_url"     : item.product.productimage_set.filter(product_id=item.product.id).first().image_url
이미 해당 `product`를 참조하고 있는 `product images`를 가져오는 과정이기때문에 추가적으로 `item.product.id` 로 필터링을 걸어야할 필요가 없겠죠?!
```suggestion
            "image_url"     : item.product.productimage_set.first().image_url
```

2020-12-23 17:46 UTC, jamessoun93 commented on order/views.py
> +                'member'           : Member.objects.get(id=request.user),
데코레이터가 주석처리되어있어서 `request.user` 을 받아올 수 없을텐데 코드 실행하여 테스트까지 해보셨을까요!?

2020-12-24 08:11 UTC, lyla0427 commented on order/views.py
> +                'member'           : Member.objects.get(id=request.user),
네 테스트했습니다!

2020-12-24 08:13 UTC, lyla0427 commented on order/views.py
> +            "image_url"     : item.product.productimage_set.filter(product_id=item.product.id).first().image_url
반영했습니다~!

2020-12-25 12:01 UTC, ulfrid reviewed
승연님 전체적으로 코드가 너무 깔끔해지고 개선되서 좋네요. 2차 프로젝트 기대하겠습니다.

2020-12-25 12:01 UTC, ulfrid commented on product/views.py
> +                average_star_rating = Review.objects.filter(product_id=product_id).aggregate(Avg('star_rating'))["star_rating__avg"]
👍

2020-12-25 12:01 UTC, ulfrid commented on user/views.py
> +        for i in recentviews:
```suggestion
        for item in recentviews:
```

2020-12-26 12:26 UTC, merged