[DMFriends 우혁준] FIX: 회원가입 엔드포인트구현
wecode-bootcamp-korea/15-1st-DMFriends-backend pull request #7
Opened 2020-12-20 04:50 UTC by hwukjunwoo

>wecode PR message template 및 체크 리스트 입니다. 

## 수정 사항 간략한 한줄 요약
- email validation 사용
- 모델명 수정
- 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-20 10:53 UTC, ulfrid requested changes
수정 부탁드립니다.

2020-12-20 10:53 UTC, ulfrid commented on user/views.py
> +#CHECK_EMAIL= re.compile('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')
사용하지 않을거라면 제거부탁드립니다.

2020-12-20 10:53 UTC, ulfrid commented on user/views.py
> +            return JsonResponse({'message': 'VALIDATION_ERROR'}, status=400)
```suggestion
            return JsonResponse({'message': 'INVALID_EMAIL'}, status=400)
```
이메일 벨리데이션 에러이기 때문에 이메세지가 더 맞을것 같습니다.

2020-12-20 15:40 UTC, ulfrid requested changes

2020-12-20 15:40 UTC, ulfrid commented on user/views.py
> +            email = data.get('email')
```suggestion
            email = data.get('email', None)
```

2020-12-20 15:40 UTC, ulfrid commented on user/views.py
> +            password = data.get('password')
```suggestion
            password = data.get('password', None)
```

2020-12-20 15:40 UTC, ulfrid commented on user/views.py
> +            return JsonResponse({'message': 'VALIDATION_EMAIL'}, status=400)
```suggestion
            return JsonResponse({'message': 'INVALID_EMAIL'}, status=400)
```

2020-12-20 15:40 UTC, ulfrid commented on user/views.py
> +                raise ValidationError('INVALID_EMAIL')
```suggestion
            if email:
               validate_email(email)
```
이렇게 바꾸는 이유는 email안에 정상적으로 키가 조회되서 데이터가 들어왔다면, 아래 함수를 실행시키면 메일에 문제가 없다면 
에러가 안날 것이고, 에러가 나면 ValidationError를 굳이 raise 안해줘도 exception이 발생하기 때문입니다.

2020-12-20 15:50 UTC, hwukjunwoo commented
수정했습니다

2020-12-21 03:41 UTC, ulfrid commented
LGTM.

2020-12-21 03:41 UTC, merged